#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Bookkeeper.Resource", IsApplication=true)]

namespace Bookkeeper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000d
			public const int To_from_textview = 2130968589;
			
			// aapt resource value: 0x7f040016
			public const int add_event_button = 2130968598;
			
			// aapt resource value: 0x7f04000f
			public const int amount_edit_text = 2130968591;
			
			// aapt resource value: 0x7f040005
			public const int checkbox_income = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int checkbox_outcome = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int create_report_btn = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int date_button = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int description_text_view = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int event_btn = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int linearLayout1 = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int linearLayout2 = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int linearLayout3 = 2130968592;
			
			// aapt resource value: 0x7f040013
			public const int linearLayout4 = 2130968595;
			
			// aapt resource value: 0x7f040004
			public const int radioGroup1 = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int tax_textview = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int taxes_spinner = 2130968594;
			
			// aapt resource value: 0x7f040003
			public const int textView1 = 2130968579;
			
			// aapt resource value: 0x7f04000e
			public const int to_from_spinner = 2130968590;
			
			// aapt resource value: 0x7f040014
			public const int total_amount_without_tax = 2130968596;
			
			// aapt resource value: 0x7f04000b
			public const int type_spinner = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int type_textview = 2130968586;
			
			// aapt resource value: 0x7f040015
			public const int updated_ammount = 2130968597;
			
			// aapt resource value: 0x7f040001
			public const int view_event_btn = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int EntryList = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int MainMenu = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int NewEvent = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
